name:                webserver
version:             0.1.0.0
github:              "githubuser/webserver"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/webserver#readme>

dependencies:
- base >= 4.7 && < 5
- scotty
- text
- wai-cors
- aeson          >= 1.4.7 && < 1.5
- aeson-pretty   >= 0.8.8 && < 0.9
- prettyprinter  >= 1.6.1 && < 1.7
- json           >= 0.10 && < 0.11
- pretty         >= 1.1.3 && < 1.2
- containers     >= 0.6.0 && < 0.7
- transformers   >= 0.5.6.2 && <= 0.5.6.2

library:
  source-dirs: src

executables:
  webserver-exe:
    main:                Main.hs
    source-dirs:
    - app
    - app/ast
    - app/util
    - app/cs
    - app/codegen
    - app/bidi
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - webserver

tests:
  webserver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - webserver
